"""Generate the 7-slide overview presentation.

Produces ``ppt/eegfmri_overview.pptx`` (gitignored) with two embedded
figures generated by matplotlib from our N=2 results (hardcoded since
results/ is gitignored). Upload the .pptx to Google Drive and open with
Google Slides; see ``ppt/IMPORT_TO_GOOGLE_SLIDES.md``.

Slide order:
  1. Preprocessing pipeline
  2. EO/EC fundamental results
  3. Other tasks (stimloc, rest alpha-BOLD GLM, SWM)
  4. Figure A — phenotype dissociation in alpha-BOLD GLM z[V1]
  5. Vigilance x WM (the headline)
  6. Figure B — load x lag x phenotype matrix (Bridwell test)
  7. Future directions

Usage:
    python scripts/generate_ppt.py
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

OUT_DIR = Path(__file__).resolve().parent.parent / "ppt"
PPTX_PATH = OUT_DIR / "eegfmri_overview.pptx"
FIG_A_PATH = OUT_DIR / "fig_a_alpha_bold_zv1.png"
FIG_B_PATH = OUT_DIR / "fig_b_lag_matrix.png"

# ---------------------------------------------------------------------------
# Data (hardcoded from results/ — single source of truth in docs/RESULTS.md)
# ---------------------------------------------------------------------------

# Per-task alpha-BOLD GLM mean z[V1].
Z_V1 = {
    "sub-500":     {"rest": -1.093, "swm_run-1": -0.473, "swm_run-2": -0.885},
    "sub-1070302": {"rest": -0.129, "swm_run-1": -0.341, "swm_run-2": -0.063},
}

# Bridwell lag sweep — fixed 8-12 Hz band, trial-level alpha-BOLD r.
LAGS = [3, 5, 7, 9, 11]
LAG_MATRIX_ROWS = [
    ("sub-500 L1",     [-0.042, -0.029, -0.159, -0.084, +0.019]),
    ("sub-500 L5",     [-0.106, -0.245, -0.216, -0.117, -0.044]),
    ("sub-1070302 L1", [+0.132, +0.152, +0.050, -0.130, -0.230]),
    ("sub-1070302 L5", [+0.168, +0.153, +0.237, +0.222, +0.095]),
]


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def make_fig_a() -> None:
    """Bar chart: mean z[V1] across 3 tasks for the two subjects."""
    tasks = ["rest", "swm_run-1", "swm_run-2"]
    labels = tasks
    xs = np.arange(len(tasks))
    w = 0.35
    sub500 = [Z_V1["sub-500"][t] for t in tasks]
    sub107 = [Z_V1["sub-1070302"][t] for t in tasks]

    fig, ax = plt.subplots(figsize=(9, 5.4))
    b1 = ax.bar(xs - w/2, sub500, w, label="sub-500 (canonical)",
                color="#2ca02c", edgecolor="black")
    b2 = ax.bar(xs + w/2, sub107, w, label="sub-1070302 (vigilance-vulnerable)",
                color="#d62728", edgecolor="black")
    ax.axhline(0, color="black", lw=1)
    ax.axhline(-1.0, color="gray", lw=0.5, ls="--", alpha=0.4)
    ax.set_xticks(xs); ax.set_xticklabels(labels, fontsize=12)
    ax.set_ylabel("mean z[V1] from alpha-BOLD GLM", fontsize=12)
    ax.set_title("Alpha-BOLD coupling in V1 — canonical phenotype stays negative\n"
                 "across rest + working memory; vigilance-vulnerable hovers near zero",
                 fontsize=13)
    ax.legend(loc="lower right", fontsize=11)
    for rects in (b1, b2):
        for r in rects:
            h = r.get_height()
            ax.text(r.get_x() + r.get_width()/2, h - 0.06 if h < 0 else h + 0.04,
                    f"{h:+.2f}", ha="center", fontsize=10)
    ax.set_ylim(-1.4, 0.4)
    ax.grid(axis="y", alpha=0.25)
    plt.tight_layout()
    plt.savefig(FIG_A_PATH, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info("wrote %s", FIG_A_PATH)


def make_fig_b() -> None:
    """Heatmap: 4 rows (subject x load) by 5 cols (HRF lag) of trial-level r."""
    data = np.array([r for _, r in LAG_MATRIX_ROWS])
    row_labels = [name for name, _ in LAG_MATRIX_ROWS]
    col_labels = [f"lag {l}" for l in LAGS]

    fig, ax = plt.subplots(figsize=(9, 5.4))
    vmax = float(np.abs(data).max()) * 1.05
    im = ax.imshow(data, cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="auto")
    ax.set_xticks(np.arange(len(col_labels)))
    ax.set_xticklabels(col_labels, fontsize=12)
    ax.set_yticks(np.arange(len(row_labels)))
    ax.set_yticklabels(row_labels, fontsize=12)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            v = data[i, j]
            color = "white" if abs(v) > vmax * 0.55 else "black"
            ax.text(j, i, f"{v:+.2f}", ha="center", va="center",
                    color=color, fontsize=11)
    ax.set_title("Trial-level alpha-BOLD coupling × WM load × HRF lag\n"
                 "Red = positive (anti-canonical), Blue = negative (canonical)",
                 fontsize=13)
    ax.set_xlabel("HRF lag (TR)", fontsize=12)
    cb = plt.colorbar(im, ax=ax)
    cb.set_label("Pearson r (across trials in load)", fontsize=11)
    # Highlight cells: canonical strengthening (sub-500 L5 lag 5)
    # and the lag-shifted vs true sign-flip cells in sub-1070302.
    for (i, j) in [(1, 1), (2, 4), (3, 2)]:  # sub-500 L5 lag5, sub-107 L1 lag11, sub-107 L5 lag7
        rect = plt.Rectangle((j-0.5, i-0.5), 1, 1, fill=False,
                             edgecolor="black", lw=2.5)
        ax.add_patch(rect)
    plt.tight_layout()
    plt.savefig(FIG_B_PATH, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info("wrote %s", FIG_B_PATH)


# ---------------------------------------------------------------------------
# Slide helpers
# ---------------------------------------------------------------------------

def add_title_only_slide(prs: Presentation, title: str) -> "Slide":
    layout = prs.slide_layouts[5]  # Title only
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    for p in slide.shapes.title.text_frame.paragraphs:
        for run in p.runs:
            run.font.size = Pt(26)
            run.font.bold = True
    return slide


def add_bullets(slide, bullets: list[str], left: float = 0.5,
                top: float = 1.4, width: float = 12.0, height: float = 5.6,
                font_size: int = 16) -> None:
    tx = slide.shapes.add_textbox(Inches(left), Inches(top),
                                  Inches(width), Inches(height))
    tf = tx.text_frame
    tf.word_wrap = True
    for i, b in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = b
        p.level = 0
        for run in p.runs:
            run.font.size = Pt(font_size)


def add_image_slide(prs: Presentation, title: str, image_path: Path,
                    caption: str) -> None:
    slide = add_title_only_slide(prs, title)
    pic = slide.shapes.add_picture(
        str(image_path), Inches(0.5), Inches(1.2),
        width=Inches(12.3), height=Inches(5.4),
    )
    cap = slide.shapes.add_textbox(Inches(0.5), Inches(6.7),
                                   Inches(12.3), Inches(0.5))
    p = cap.text_frame.paragraphs[0]
    p.text = caption
    for run in p.runs:
        run.font.size = Pt(13)
        run.font.italic = True


# ---------------------------------------------------------------------------
# Build the deck
# ---------------------------------------------------------------------------

def build_pptx() -> None:
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Slide 1 — Preprocessing pipeline
    s = add_title_only_slide(prs, "1.  Preprocessing pipeline")
    add_bullets(s, [
        "Dataset: UCLA simultaneous EEG-fMRI cohort. Siemens Prisma 3T, 128-ch EGI HydroCel, TR=1s multiband-4.",
        "Processed N=2: sub-500 (canonical phenotype) + sub-1070302 (vigilance-vulnerable phenotype).",
        "",
        "EEG pipeline:  BIDS loader  →  MR-gradient artefact removal  →  BCG (ballistocardiogram) removal  →  resample 250 Hz  →  braindecode datasets.",
        "fMRI pipeline:  nibabel load  →  ANTs rigid-body motion correction  →  per-subject stimloc functional V1 localiser  →  nilearn FirstLevelModel (Glover HRF, 6 mm smoothing, motion + cosine drift nuisance).",
        "",
        "Disk cache layer (scripts/_cache.py): cleaned MNE Raws and motion-corrected NIfTIs cached under derivatives/cache/, saving ~12 min per rerun.",
        "All experiments reproducible from sbatch templates on the Delta bbnv-delta-gpu allocation.",
    ])

    # Slide 2 — EO/EC fundamental results
    s = add_title_only_slide(prs, "2.  Eyes-Open / Eyes-Closed (Berger) — first phenotype signature")
    add_bullets(s, [
        "EEG occipital alpha EC/EO power ratio (Berger 1929):",
        "  •  sub-500 outside scanner: 3.10×, p = 2 × 10⁻⁵, Cohen's d = 0.94  →  textbook canonical alpha enhancement when eyes closed.",
        "  •  sub-500 inside scanner: attenuated by gradient/BCG residuals (0.99×) but classifier 88 % accurate.",
        "  •  sub-1070302 inside scanner: ratio = 0.85× — REVERSED. Alpha higher when eyes are open.",
        "",
        "fMRI EOEC within-subject classifier (PCA50 + LinearSVC, paired-block CV):",
        "  •  sub-500 92 % accuracy; sub-1070302 89 % accuracy — both subjects' brains do distinguish EC vs EO.",
        "  •  But sub-1070302's V1 BOLD direction is reversed (EC > EO instead of EO > EC).",
        "",
        "Two independent modalities (EEG alpha + fMRI V1 BOLD) both show reversal in the same subject. First evidence of a vigilance-related cross-modal anomaly.",
    ])

    # Slide 3 — Other tasks
    s = add_title_only_slide(prs, "3.  Rest, stimloc, working-memory — pipeline extension")
    add_bullets(s, [
        "Stimloc functional V1 localiser (z > 2.3, top-1 % fallback):",
        "  •  sub-500: 194 voxels (z_max 3.55) — smaller mask but real signal.    sub-1070302: 3547 voxels (z_max 6.20) — clean V1 map.",
        "",
        "Rest task alpha-BOLD coupling GLM (Goldman 2002 paradigm):",
        "  •  sub-500 z[V1] = −1.09, 86 % negative voxels  →  textbook canonical alpha-BOLD anticorrelation.",
        "  •  sub-1070302 z[V1] = −0.08, 52 % negative voxels  →  essentially absent. The same subject who reversed on EOEC now shows broken alpha-BOLD coupling at rest.",
        "",
        "HRF-lag whole-run cross-correlation (−2 to +12 TR):",
        "  •  sub-500 lag stable at 4–6 TR across all 3 tasks (rest + swm-1 + swm-2) — canonical Glover HRF.",
        "  •  sub-1070302 has signal only at rest (lag 7); collapses on swm runs (|r| < 0.05 at any lag).",
        "",
        "Voxelwise reliability test (ICC 3,1 across rest + swm runs): ≈ 0 in both subjects → voxelwise scale not a viable biomarker.",
    ])

    # Slide 4 — Figure A
    add_image_slide(
        prs,
        "Figure 1 — phenotype dissociation in V1 alpha-BOLD coupling",
        FIG_A_PATH,
        "Mean z[V1] from per-task alpha-BOLD GLM. "
        "sub-500 (green) stays canonical-negative across rest and both working-memory runs. "
        "sub-1070302 (red) hovers near zero — vigilance-vulnerable phenotype.",
    )

    # Slide 5 — Vigilance × WM
    s = add_title_only_slide(prs, "4.  Vigilance × Working-Memory — the headline finding")
    add_bullets(s, [
        "Trial-locked Sternberg analysis (n = 80 trials per subject, balanced load 1 vs load 5):",
        "",
        "Behaviour: sub-1070302 pays a 2× larger accuracy decrement under load (−10 % vs sub-500's −5 %).",
        "          Speed-accuracy strategies diverge: sub-500 slows by 153 ms to preserve accuracy; sub-1070302 keeps speed and loses accuracy.",
        "",
        "Trial-level alpha-BOLD coupling × WM load × HRF lag (the main result, see Figure 2):",
        "  •  sub-500: canonical negative coupling at the textbook 5-TR HRF lag; STRENGTHENS 8× under high WM load (−0.029 → −0.245).",
        "  •  sub-1070302 at low load: LAG-SHIFTED canonical — coupling reaches −0.23 at lag 11 instead of lag 5 (Bridwell-2025 phenomenon).",
        "  •  sub-1070302 at high load: TRUE sign inversion — coupling positive (+0.15 to +0.24) at every HRF lag tested.",
        "",
        "Vigilance × RT validity: alpha tracks reaction time only in sub-1070302 (r = +0.12) — the alpha-as-vigilance marker is itself subject-conditional.",
        "",
        "Seven independent measurements (EOEC alpha, EOEC V1, rest alpha-BOLD, HRF lag, WM behaviour, lag matrix, vigilance-RT) all dissociate the two phenotypes the same way.",
    ])

    # Slide 6 — Figure B
    add_image_slide(
        prs,
        "Figure 2 — load × HRF-lag × phenotype matrix (Bridwell-2025 lag sweep)",
        FIG_B_PATH,
        "Trial-level Pearson r between posterior alpha (engaged window) and V1 BOLD at lags 3-11 TR. "
        "Highlighted cells: sub-500 L5 lag5 (canonical strengthening), sub-1070302 L1 lag11 (lag-shifted canonical), sub-1070302 L5 lag7 (true sign inversion).",
    )

    # Slide 7 — Future directions
    s = add_title_only_slide(prs, "5.  Future directions — scaling to n=156")
    add_bullets(s, [
        "Literature gap verified novel (2022-2026): no published work has reported a load × HRF-lag × vigilance-phenotype three-way interaction in trial-level alpha-BOLD coupling in V1.",
        "Closest precedents — Scheeringa 2009, Michels 2010, Meltzer 2007, Bridwell 2025, Jiříček 2026 — explicitly differentiated in the proposal.",
        "",
        "Pre-registered hypotheses (OSF lock before access):",
        "  H1  bimodal across-subject distribution of (Δ r load5 − load1)",
        "  H2  load-dependent transition signature in ≥ 15 % of cohort",
        "  H3  Bridwell extension: load1 vulnerable-cluster shows lag ≥ 9 TR canonical",
        "  H4  cluster predicts independent 5-element vigilance covariate vector",
        "  H5  vulnerable cluster has ≥ 2× larger WM accuracy decrement",
        "  H6  vigilance × RT validity is cluster-conditional",
        "",
        "Methodological hardening underway on the N=2 data:",
        "  •  IAF-band sensitivity test  (Risk C — alpha peak-frequency confound — in progress)",
        "  •  Flexible HRF basis (canonical + temporal + dispersion derivatives, Risk A)",
        "  •  FOOOF/specparam aperiodic-1/f decomposition (missed-risk #2)",
        "",
        "Resources: 6-week analyst budget, bbnv-delta-gpu allocation (already funded). No additional compute requested.",
        "Ask: read access to the n=156 BIDS root + 30-min kickoff meeting before OSF lock. Co-authorship on the resulting paper.",
    ])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    prs.save(str(PPTX_PATH))
    log.info("wrote %s", PPTX_PATH)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    make_fig_a()
    make_fig_b()
    build_pptx()
    print("\nDone.")
    print(f"  Figures:     {FIG_A_PATH}\n               {FIG_B_PATH}")
    print(f"  Deck:        {PPTX_PATH}")
    print(f"  Slides total: {len(Presentation(str(PPTX_PATH)).slides)}")
    print("\nTo open in Google Slides, see ppt/IMPORT_TO_GOOGLE_SLIDES.md")


if __name__ == "__main__":
    main()
